os:
  - osx

language: python

python:
  - "2.6"
  - "2.7"

install:
  - /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  - brew update
  - brew outdated xctool || brew upgrade xctool
  - brew install opencv

script:
  - python setup.py install

